#heroku:
#  stage: deploy
#  only:
#    - master
#  script:
#    - git config --global user.email "pranay.srivastava.17.1@mountblue.tech"
#    - git config --global user.name "NeerajTiwari17"
#    - rm -rf .git
#    - git init
#    - git add .
#    - git commit -m "deployed"
#    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/test-auto-deploy.git
#    - git push -f heroku master
deploy_heroku:
  variables:
    HEROKU_API_KEY: "48096d5f-8294-46dd-9ce2-f58230d78088"
  image: centos
  stage: deploy
  environment: heroku
  only:
    - master
  script:
    - echo "Deploying for Heroku Cloud Platform"
    - echo "$HEROKU_API_KEY"
    - yum install git -y
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/stackoverflow-application.git
    - git config --global user.email "pranay.srivastava.17.1@mountblue.tech"
    - git config --global user.name "pranay.srivastava.17.1"
    - git config --global push.default matching
    - git checkout master
    - git commit --allow-empty -m "Heroku build trigger notification"
    - git push -f heroku HEAD:master
